openapi: 3.0.3
info:
  title: Kids Photo Insights API
  version: 0.1.0
servers:
  - url: https://api.example.com
    description: Placeholder server
security:
  - ApiKeyAuth: []
paths:
  /v1/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /v1/analyze-photo:
    post:
      summary: Analyze a child photo to infer state, mood, weather and suggestions
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [imageBase64, timestamp]
              properties:
                imageBase64:
                  type: string
                  description: Base64-encoded image payload
                timestamp:
                  type: string
                  format: date-time
                childId:
                  type: string
                  nullable: true
                preferences:
                  type: object
                  properties:
                    retentionDays:
                      type: integer
                      default: 7
                    region:
                      type: string
                      description: Processing region hint (optional)
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResult'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Server error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    SuggestionItem:
      type: object
      required: [name]
      properties:
        name:
          type: string
        qty:
          type: number
          nullable: true
        unit:
          type: string
          nullable: true
    Suggestion:
      type: object
      required: [id, category, items, reasoning]
      properties:
        id:
          type: string
        category:
          type: string
          enum: [出行, 健康, 学习, 娱乐, 其他]
        items:
          type: array
          items:
            $ref: '#/components/schemas/SuggestionItem'
        reasoning:
          type: string
        source:
          type: string
          enum: [analysis, user, template]
          nullable: true
    AnalysisResult:
      type: object
      properties:
        childState:
          type: string
          enum: [活跃, 疲劳, 专注, 放松, 不适]
          nullable: true
        mood:
          type: string
          enum: [愉快, 平静, 沮丧, 兴奋, 疲劳]
          nullable: true
        weather:
          type: string
          enum: [晴, 多云, 雨, 雪, 阴, 风]
          nullable: true
        tags:
          type: array
          items:
            type: string
        confidence:
          type: number
          minimum: 0
          maximum: 1
        notes:
          type: string
          nullable: true
        suggestions:
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'