version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: kpi
      POSTGRES_USER: kpi
      POSTGRES_PASSWORD: kpi_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    # 如有后端源代码，可替换为 build: ../../../../backend
    image: your-org/kpi-backend:latest
    depends_on:
      - postgres
      - minio
    environment:
      API_KEY: dev-key
      DATABASE_URL: postgres://kpi:kpi_password@postgres:5432/kpi
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: kids-photo-temp
      RETENTION_DAYS: 7
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pg_data:
  minio_data: